#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pure-sasl
Version  : 0.6.2
Release  : 2
URL      : https://files.pythonhosted.org/packages/83/b7/a0d688f86c869073cc28c0640899394a1cf68a6d87ee78a09565e9037da6/pure-sasl-0.6.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/83/b7/a0d688f86c869073cc28c0640899394a1cf68a6d87ee78a09565e9037da6/pure-sasl-0.6.2.tar.gz
Summary  : Pure Python client SASL implementation
Group    : Development/Tools
License  : MIT
Requires: pure-sasl-python = %{version}-%{release}
Requires: pure-sasl-python3 = %{version}-%{release}
Requires: kerberos
BuildRequires : buildreq-distutils3
BuildRequires : kerberos

%description
pure-sasl
=========
.. image:: https://travis-ci.org/thobbs/pure-sasl.png?branch=master
:target: https://travis-ci.org/thobbs/pure-sasl

%package python
Summary: python components for the pure-sasl package.
Group: Default
Requires: pure-sasl-python3 = %{version}-%{release}

%description python
python components for the pure-sasl package.


%package python3
Summary: python3 components for the pure-sasl package.
Group: Default
Requires: python3-core
Provides: pypi(pure_sasl)

%description python3
python3 components for the pure-sasl package.


%prep
%setup -q -n pure-sasl-0.6.2
cd %{_builddir}/pure-sasl-0.6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1584473231
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
